
services:
  migrations:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    volumes:
      - ./:/home/mediacms.io/mediacms/
    command: "python manage.py migrate"
    environment:
      DEVELOPMENT_MODE: "True"
    restart: on-failure

  frontend:
    image: node:14
    volumes:
      - ${PWD}/frontend:/home/mediacms.io/mediacms/frontend/
    working_dir: /home/mediacms.io/mediacms/frontend/
    command: bash -c "npm install && npm run start"
    env_file:
      - ${PWD}/frontend/.env
    ports:
      - "8088:8088"
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    command: "python manage.py runserver 0.0.0.0:80"
    environment:
      DEVELOPMENT_MODE: "True"
      ADMIN_USER: 'admin'
      ADMIN_PASSWORD: 'admin'
      ADMIN_EMAIL: 'admin@localhost'
    ports:
      - "80:80"
    volumes:
      - ./:/home/mediacms.io/mediacms/
    depends_on:
      - migrations

  celery_worker:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    deploy:
      replicas: 1
    volumes:
      - ./:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - web
