x-common-variables: &common-variables
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  DEBUG: ${DEBUG}

services:
  migrations:
    image: mediacms/mediacms:latest
    volumes:
      - settings:/home/mediacms.io/mediacms/deploy/docker/
    environment:
      <<: *common-variables
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: 'admin'
      ADMIN_EMAIL: 'admin@localhost'
      #ADMIN_PASSWORD: 'uncomment_and_set_password_here'
    command: "./deploy/docker/prestart.sh"
    restart: on-failure
  web:
    image: mediacms/mediacms:latest
    deploy:
      replicas: 1
    ports:
      - "80:80"
    volumes:
      - media_store:/home/mediacms.io/mediacms/media_files/
      - static:/home/mediacms.io/mediacms/static/
      - settings:/home/mediacms.io/mediacms/deploy/docker/
    environment:
      <<: *common-variables
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations

  celery_beat:
    image: mediacms/mediacms:latest
    volumes:
      - settings:/home/mediacms.io/mediacms/deploy/docker/
    environment:
      <<: *common-variables
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'

  celery_worker:
    image: mediacms/mediacms:latest
    deploy:
      replicas: 1
    volumes:
      - media:/home/mediacms.io/mediacms/media_files/
      - static:/home/mediacms.io/mediacms/static/
      - settings:/home/mediacms.io/mediacms/deploy/docker/
    environment:
      <<: *common-variables
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations


volumes:
  settings:
  media:
  static: